version: "3.9"
services:
  plex:
    container_name: plexserver
    image: plexinc/pms-docker:public
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - TZ=<time-zone>
      - PLEX_CLAIM=<claim-token>
      - ALLOWED_NETWORKS=<local-net/subnet>
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - /plexserver/config:/config
      - /nas/plexserverdatabase:/database
      - /nas/plexserverdatabasebackup:/databasebackup
      - /nas/plexserverphysicalmedia:/physicalmedia
      - /nas/plexservertempmedia:/tempmedia     
      - /nas/plexservertranscode:/transcode

