version: "3.9"
services:
  plex:
    container_name: plexserver
    image: plexinc/pms-docker:public
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=<time-zone>
      - PLEX_CLAIM=<claim-token>
      - ALLOWED_NETWORKS=<local-net/subnet>
    volumes:
      - /plexserver/config:/config
      - /nas/plexserverdatabase:/database
      - /nas/plexserverdatabasebackup:/databasebackup
      - /nas/plexserverphysicalmedia:/physicalmedia
      - /nas/plexservertempmedia:/tempmedia     
      - /nas/plexservertranscode:/transcode
      - /nas/plexserveroptimizedmedia:/optimized

