version: '3'
services:
  bind9:
    container_name: dnsserver
    image: ubuntu/bind9
    restart: unless-stopped
    environment:
      - BIND9_USER=root
      - TZ=<time-zone>
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    ports:
      - '53:53'
      - '53:53/udp'