version: "3.3"
services:
  speedtest:
    container_name: openspeedtestserver
    image: openspeedtest/latest
    restart: unless-stopped
    environment:
      - ENABLE_LETSENCRYPT=True
      - DOMAIN_NAME=<domain-name>
      - USER_EMAIL=<server-owner-email>
      - VERIFY_OWNERSHIP="TXT-FILE-CONTENT"
    ports:
      - '3000:3000'
      - '3001:3001'